baseURL = 'https://transformingthevalley.org/'
title = 'TRANSforming The Valley'
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[languages]
  [languages.en]
    title = "TRANSforming The Valley"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  custom_css = []
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke.social.follow]
networks = [
  "facebook",
  "discord",
]

[params.ananke.social.discord]
username = "rGCcCxknfH"

[params.ananke.social.facebook]
username = "transformingthevalley"

[params.ananke.social.networks.discord]
slug = "discord"
label = "Discord"
color = "#0077b5"
profile = "https://discord.com/invite/%s"
icon = "discord" # font awesome brand icon name
[params.ananke.social.networks.discord.particles]
url = "permalink"
title = "title"
summary = "description"
source = "permalink"
params = "mini=true"
